<?php

//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author:    Ashley Kitson                                                  //
// Copyright: (c) 2004, Ashley Kitson
// URL:       http://akitson.bbcb.co.uk                                      //
// Project:   The XOOPS Project (https://www.xoops.org/)                      //
// Module:    Code Data Management (CDM)                                     //
// ------------------------------------------------------------------------- //
/**
 * Xoops module Installation parameters
 *
 * This file conforms to the Xoops standard for the xoops_version.php file.
 *
 * @author        Ashley Kitson http://akitson.bbcb.co.uk
 * @copyright (c) 2004, Ashley Kitson
 * @global array Module Installation array as per Xoops
 */
global $modversion;

$modversion['name'] = _MI_CDM_NAME;
$modversion['version'] = 1.3;
$modversion['description'] = _MI_CDM_DESC;
$modversion['credits'] = 'Ashley Kitson<br>( http://akitson.bbcb.co.uk/ )';
$modversion['author'] = 'Ashley Kitson';
$modversion['help'] = 'cdmhelp.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/cdm_slogo.png';
$modversion['dirname'] = 'cdm';
$modversion['onUpdate'] = 'install_funcs.php';
$modversion['onInstall'] = 'install_funcs.php';
$modversion['onUninstall'] = 'install_funcs.php';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'cdm_meta';
$modversion['tables'][1] = 'cdm_code';

// Main Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_CDM_SMNAME1;
$modversion['sub'][1]['url'] = 'cdm_codes_list.php';
$modversion['sub'][2]['name'] = _MI_CDM_SMNAME2;
$modversion['sub'][2]['url'] = 'cdm_update.php';
$modversion['sub'][3]['name'] = _MI_CDM_SMNAME3;
$modversion['sub'][3]['url'] = 'cdmhelp.php';
// Templates
$modversion['templates'][1]['file'] = 'cdm_list_codes.tpl';
$modversion['templates'][1]['description'] = 'Simple list of codes';
$modversion['templates'][2]['file'] = 'cdm_index.tpl';
$modversion['templates'][2]['description'] = 'Select and edit set of codes';
$modversion['templates'][3]['file'] = 'cdm_meta_edit.tpl';
$modversion['templates'][3]['description'] = 'Edit a meta record';
$modversion['templates'][4]['file'] = 'cdm_codes_edit.tpl';
$modversion['templates'][4]['description'] = 'Edit a code record';
$modversion['templates'][5]['file'] = 'cdm_db_update.tpl';
$modversion['templates'][5]['description'] = 'Edit a code record';

// Admin things
$modversion['hasAdmin'] = 0;
$modversion['hasSearch'] = 0;
$modversion['hasComments'] = 0;
$modversion['hasNotification'] = 0;
